name: Generate Datas

on:

  schedule: # executeevery12 hours
     - cron: "* */12 * * *"
     workflow_dispatch:
     
     obs
      build:
        name: Joobs to update datas
        runs-on: ubuntu-latest
        steps:
        # Sake Animation
        - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: wellington-amaral
          svg_out_path: dist/github-contribuition-grid-snake.svg
          
          -uses: crazy-max/ghaction-github-pages@v2.1.3
          with:
          target_branch: output
          build_dir: dist
          env:
          GITHUB_TOKEN: ${{ secrets.GITHB_TOKEN }}
